### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by Juanflugel** [googlecodelabs/android-testing#244]
Unable to run the app when using Android Studio 4.2.
"e: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException"

4. Step 1: Run the sample app

Download the sample code and try to run it using android studio 4.2

I tryied a lot of of things, from trying to use JDK version 8 to differents gradle configurations, but nothing worked

**codelab:** Advanced Android in Kotlin 05.1: Testing Basics

**Comment by Dannark** [comment]
I found the solution... Android Studio **4.2.0** and more now comes with Java **11.0.8** shipped and will use it by default which cases this error in deprecated libraries.

The solution is simple, you need to change it to **java (JDK) 1.8** in the menu `File > Project Structure > JDK Location`

![image](https://user-images.githubusercontent.com/7622553/117518419-046a2900-af76-11eb-8731-0ba4a1d1a481.png)

Notices that Android Studio lower than 4.2.0 comes with java 1.8 already

**Comment by JoseAlcerreca** [comment]
This has been fixed to work with AS 4.2.1
